package com.google.android.gms.fit.samples.basichistoryapi.mpchartlib.listener;

import com.google.android.gms.fit.samples.basichistoryapi.mpchartlib.data.ChartEntry;
import com.google.android.gms.fit.samples.basichistoryapi.mpchartlib.data.DataSet;

/**
 * Listener for callbacks when drawing on the chart.
 * 
 * @author Philipp
 * 
 */
public interface OnDrawListener {

	/**
	 * Called whenever an chartEntry is added with the finger. Note this is also called for entries that are generated by the
	 * library, when the touch gesture is too fast and skips points.
	 * 
	 * @param chartEntry
	 *            the last drawn chartEntry
	 */
	void onEntryAdded(ChartEntry chartEntry);

	/**
	 * Called whenever an chartEntry is moved by the user after beeing highlighted
	 * 
	 * @param chartEntry
	 */
	void onEntryMoved(ChartEntry chartEntry);

	/**
	 * Called when drawing finger is lifted and the draw is finished.
	 * 
	 * @param dataSet
	 *            the last drawn DataSet
	 */
	void onDrawFinished(DataSet<?> dataSet);

}
